import { auditEvent, type AuditRepository } from "@/platform/audit";
import { ValidationError, NotFoundError } from "@/platform/errors";
import type { TenantContext } from "@/platform/context";
import type { EmployeeRepository } from "@/platform/people/employee-repository";
import { requirePeoplePermission } from "@/platform/people/application/people-policies";
import { validateEmployeeId } from "@/platform/people/application/people-validators";
import { toEmployeeContactDto, toEmployeeDirectoryDto, toEmployeeGovernmentIdsDto, toEmployeeProfileDto } from "@/platform/people/application/people-dtos";
import type { EmployeeContactDto, EmployeeDirectoryDto, EmployeeGovernmentIdsDto, EmployeeListInput, EmployeeListResult, EmployeeProfileDto, EmployeeSearchInput, EmployeeSearchResult } from "@/platform/people/application/people-dtos";
const unwrap = <T,>(result: ReturnType<typeof validateEmployeeId> | { success: true; data: T } | { success: false; issues: unknown[] }): T => { if (!result.success) throw new ValidationError("Validation failed.", { issues: result.issues }); return result.data as T; };
export interface PeopleService { getProfile(context: TenantContext, employeeId: string): Promise<EmployeeProfileDto>; getContact(context: TenantContext, employeeId: string): Promise<EmployeeContactDto>; list(context: TenantContext, input?: EmployeeListInput): Promise<EmployeeListResult>; search(context: TenantContext, input: EmployeeSearchInput): Promise<EmployeeSearchResult>; getGovernmentIds(context: TenantContext, employeeId: string): Promise<EmployeeGovernmentIdsDto>; }
export class PeopleApplicationService implements PeopleService {
  constructor(private readonly employees: EmployeeRepository, private readonly audits: AuditRepository) {}
  async getProfile(context: TenantContext, employeeId: string) { requirePeoplePermission(context, "people.read"); const employee = await this.employees.findById(context, unwrap(validateEmployeeId(employeeId))); if (!employee) throw new NotFoundError("Employee"); return toEmployeeProfileDto(employee); }
  async getContact(context: TenantContext, employeeId: string) { requirePeoplePermission(context, "people.read"); const employee = await this.employees.findById(context, unwrap(validateEmployeeId(employeeId))); if (!employee) throw new NotFoundError("Employee"); return toEmployeeContactDto(employee); }
  async list(context: TenantContext, input: EmployeeListInput = {}): Promise<EmployeeListResult> { requirePeoplePermission(context, "people.read"); const offset = Math.max(0, input.offset ?? 0); const limit = Math.min(100, Math.max(1, input.limit ?? 25)); const direction = input.sortDirection === "desc" ? -1 : 1; let items = (await this.employees.list(context)).filter((employee) => (!input.department || employee.employment.departmentId === input.department) && (!input.employmentStatus || employee.status === input.employmentStatus)).map(toEmployeeDirectoryDto); items = items.sort((a, b) => ((input.sortBy === "employeeNumber" ? a.employeeNumber : a.displayName).localeCompare(input.sortBy === "employeeNumber" ? b.employeeNumber : b.displayName) * direction)); return { items: items.slice(offset, offset + limit), offset, limit, total: items.length }; }
  async search(context: TenantContext, input: EmployeeSearchInput): Promise<EmployeeSearchResult> { requirePeoplePermission(context, "people.read"); const limit = Math.min(50, Math.max(1, input.limit ?? 25)); const query = input.query.trim(); if (!query) throw new ValidationError("Search query is required."); const items = (await this.employees.search(context, query)).map(toEmployeeDirectoryDto).sort((a, b) => a.displayName.localeCompare(b.displayName)); return { items: items.slice(0, limit), limit, total: items.length }; }
  async getGovernmentIds(context: TenantContext, employeeId: string) { requirePeoplePermission(context, "people.government_ids.read"); const employee = await this.employees.findById(context, unwrap(validateEmployeeId(employeeId))); if (!employee) throw new NotFoundError("Employee"); await this.audits.append(auditEvent(context, { module: "people", action: "employee.government_ids.viewed", targetId: employee.id })); return toEmployeeGovernmentIdsDto(employee); }
}
