import { describe, expect, it } from "vitest";
import { InMemoryAuditRepository } from "@/platform/audit";
import { InMemoryEmployeeRepository } from "@/platform/people/in-memory-employee-repository";
import { PeopleApplicationService } from "@/platform/people/application/people-service";
import { AuthorizationError } from "@/platform/errors";
import { createPlatformContainer } from "@/platform/composition-root";
import { PEOPLE_SERVICE } from "@/platform/tokens";
import { PermissionSet, type TenantContext } from "@/platform/context";

const context: TenantContext = { tenantId: "nw-ph", actorId: "user-1", actorName: "HR Admin", roles: ["hr_admin"], permissions: new PermissionSet(["people.read"]), correlationId: "test-request", authenticationMethod: "test", actorProvenance: "server_verified" };
describe("PeopleApplicationService", () => { it("returns bounded deterministic directory results", async () => { const service = new PeopleApplicationService(new InMemoryEmployeeRepository(), new InMemoryAuditRepository()); const result = await service.list(context, { limit: 2, sortBy: "name" }); expect(result.items).toHaveLength(2); expect(result.total).toBeGreaterThan(2); expect(result.items[0].displayName <= result.items[1].displayName).toBe(true); }); it("audits Government ID reads without sensitive metadata", async () => { const repository = new InMemoryEmployeeRepository(); const audit = new InMemoryAuditRepository(); const service = new PeopleApplicationService(repository, audit); const employee = (await repository.list(context))[0]; await service.getGovernmentIds(context, employee.id); expect(audit.events[0]).toMatchObject({ action: "employee.government_ids.viewed", targetId: employee.id }); expect(audit.events[0].metadata).toBeUndefined(); }); });
describe("People platform boundaries", () => { it("resolves PeopleService through DI", () => { expect(createPlatformContainer().resolve(PEOPLE_SERVICE)).toBeInstanceOf(PeopleApplicationService); }); it("prevents unauthorized reads", async () => { const service = new PeopleApplicationService(new InMemoryEmployeeRepository(), new InMemoryAuditRepository()); await expect(service.list({ ...context, roles: ["employee"] })).rejects.toBeInstanceOf(AuthorizationError); }); it("returns directory DTOs without sensitive fields", async () => { const service = new PeopleApplicationService(new InMemoryEmployeeRepository(), new InMemoryAuditRepository()); const item = (await service.list(context, { limit: 1 })).items[0]; expect(item).not.toHaveProperty("governmentIds"); expect(item).not.toHaveProperty("phone"); expect(item).not.toHaveProperty("address"); }); it("rejects blank search", async () => { const service = new PeopleApplicationService(new InMemoryEmployeeRepository(), new InMemoryAuditRepository()); await expect(service.search(context, { query: " " })).rejects.toThrow("Search query is required"); }); });
