import type { Prisma, PrismaClient } from "@prisma/client";
import type { OutboxMessage } from "@/platform/outbox/outbox-message";
import type { OutboxRepository } from "@/platform/outbox/outbox-repository";

type Client = Pick<PrismaClient, "outboxMessage">;
type ClaimClient = Client & Pick<PrismaClient, "$transaction">;
type Stored = { messageId: string; eventId: string; tenantId: string; eventName: string; aggregateType: string; aggregateId: string; correlationId: string; occurredAt: Date; payload: Prisma.JsonValue; state: string; attempts: number; availableAt: Date; processedAt: Date | null; leaseOwner: string | null; processingStartedAt: Date | null; leaseExpiresAt: Date | null; lastErrorCode: string | null; lastError: string | null };
const map = (value: Stored): OutboxMessage => Object.freeze({ messageId: value.messageId, eventId: value.eventId, tenantId: value.tenantId, eventName: value.eventName, aggregateType: value.aggregateType, aggregateId: value.aggregateId, correlationId: value.correlationId, occurredAt: value.occurredAt.toISOString(), payload: value.payload as Record<string, unknown>, state: value.state as OutboxMessage["state"], attempts: value.attempts, availableAt: value.availableAt.toISOString(), ...(value.processedAt ? { processedAt: value.processedAt.toISOString() } : {}), ...(value.leaseOwner ? { leaseOwner: value.leaseOwner } : {}), ...(value.processingStartedAt ? { processingStartedAt: value.processingStartedAt.toISOString() } : {}), ...(value.leaseExpiresAt ? { leaseExpiresAt: value.leaseExpiresAt.toISOString() } : {}), ...(value.lastErrorCode ? { lastErrorCode: value.lastErrorCode } : {}), ...(value.lastError ? { lastError: value.lastError } : {}) });

/** PostgreSQL row lock + SKIP LOCKED makes selection and lease ownership one atomic claim. */
export class PrismaOutboxRepository implements OutboxRepository {
  constructor(private readonly prisma: Client) {}
  async append(messages: readonly OutboxMessage[]): Promise<void> { for (const message of messages) await this.prisma.outboxMessage.create({ data: { messageId: message.messageId, eventId: message.eventId, tenantId: message.tenantId, eventName: message.eventName, aggregateType: message.aggregateType, aggregateId: message.aggregateId, correlationId: message.correlationId, occurredAt: new Date(message.occurredAt), payload: message.payload as Prisma.InputJsonValue, state: "pending", attempts: 0, availableAt: new Date(message.availableAt) } }); }
  async claimNext(input: Readonly<{ now: string; leaseOwner: string; leaseExpiresAt: string }>): Promise<OutboxMessage | undefined> {
    const client = this.prisma as ClaimClient;
    return client.$transaction(async (transaction) => {
      const rows = await transaction.$queryRaw<Stored[]>`SELECT * FROM "outbox_messages" WHERE ("state" IN ('pending', 'retry') AND "available_at" <= ${new Date(input.now)}) OR ("state" = 'processing' AND "lease_expires_at" <= ${new Date(input.now)}) ORDER BY "available_at", "created_at" FOR UPDATE SKIP LOCKED LIMIT 1`;
      const row = rows[0]; if (!row) return undefined;
      const result = await transaction.outboxMessage.updateMany({ where: { messageId: row.messageId, OR: [{ state: { in: ["pending", "retry"] }, availableAt: { lte: new Date(input.now) } }, { state: "processing", leaseExpiresAt: { lte: new Date(input.now) } }] }, data: { state: "processing", attempts: { increment: 1 }, leaseOwner: input.leaseOwner, processingStartedAt: new Date(input.now), leaseExpiresAt: new Date(input.leaseExpiresAt), lastError: null, lastErrorCode: null } });
      if (result.count !== 1) return undefined;
      return map({ ...row, state: "processing", attempts: row.attempts + 1, leaseOwner: input.leaseOwner, processingStartedAt: new Date(input.now), leaseExpiresAt: new Date(input.leaseExpiresAt), lastError: null, lastErrorCode: null });
    });
  }
  async markProcessed(input: Readonly<{ messageId: string; leaseOwner: string; processedAt: string }>): Promise<boolean> { const result = await this.prisma.outboxMessage.updateMany({ where: { messageId: input.messageId, state: "processing", leaseOwner: input.leaseOwner }, data: { state: "processed", processedAt: new Date(input.processedAt), leaseOwner: null, processingStartedAt: null, leaseExpiresAt: null } }); return result.count === 1; }
  async scheduleRetry(input: Readonly<{ messageId: string; leaseOwner: string; availableAt: string; errorCode: string }>): Promise<boolean> { const result = await this.prisma.outboxMessage.updateMany({ where: { messageId: input.messageId, state: "processing", leaseOwner: input.leaseOwner }, data: { state: "retry", availableAt: new Date(input.availableAt), leaseOwner: null, processingStartedAt: null, leaseExpiresAt: null, lastErrorCode: input.errorCode, lastError: "Processing failed." } }); return result.count === 1; }
  async deadLetter(input: Readonly<{ messageId: string; leaseOwner: string; occurredAt: string; errorCode: string }>): Promise<boolean> { const result = await this.prisma.outboxMessage.updateMany({ where: { messageId: input.messageId, state: "processing", leaseOwner: input.leaseOwner }, data: { state: "dead_letter", availableAt: new Date(input.occurredAt), leaseOwner: null, processingStartedAt: null, leaseExpiresAt: null, lastErrorCode: input.errorCode, lastError: "Processing stopped." } }); return result.count === 1; }
  async inspect() { const rows = await this.prisma.outboxMessage.findMany({ select: { state: true, attempts: true, availableAt: true, leaseExpiresAt: true, lastErrorCode: true }, orderBy: { createdAt: "asc" } }); return rows.map((row) => ({ state: row.state as OutboxMessage["state"], attempts: row.attempts, availableAt: row.availableAt.toISOString(), ...(row.leaseExpiresAt ? { leaseExpiresAt: row.leaseExpiresAt.toISOString() } : {}), ...(row.lastErrorCode ? { lastErrorCode: row.lastErrorCode } : {}) })); }
}
