export const CAPABILITY_STATUSES = ["ACTIVE_RUNTIME", "ACTIVE_LEGACY", "DEFERRED_VISIBLE", "DEFERRED_HIDDEN", "BLOCKED_SECURITY", "PLANNED", "RETIRED_APPROVED"] as const;
export const MIGRATION_DISPOSITIONS = ["PRESERVE", "MIGRATE_NOW", "MIGRATE_AFTER_AUTH", "MIGRATE_AFTER_PERSISTENCE", "MIGRATE_AFTER_NEW_CONTRACT", "MOVE_TO_ANOTHER_MODULE", "KEEP_EXCLUDED", "RETIRE_WITH_APPROVAL"] as const;
export type CapabilityStatus = typeof CAPABILITY_STATUSES[number];
export type MigrationDisposition = typeof MIGRATION_DISPOSITIONS[number];

export interface BusinessCapability {
  id: string; name: string; module: "People"; businessPurpose: string; actor: string;
  entryPoint: string; implementation: string; runtimeStatus: CapabilityStatus;
  sensitivity: "internal" | "personal" | "sensitive" | "restricted"; access: "read" | "write";
  permission?: string; serviceOrCommand: string; readModel?: string; persistence: string;
  auditEvent?: string; tenantIsolation: "required"; masking: "none" | "default" | "required";
  testCoverage: string; browserVerification: string; migrationDisposition: MigrationDisposition;
  dependencies: string; notesRisks: string;
}

const cap = (id: string, name: string, overrides: Partial<BusinessCapability> = {}): BusinessCapability => ({
  id, name, module: "People", businessPurpose: name, actor: "authorized People user", entryPoint: "People UI",
  implementation: "runtime boundary", runtimeStatus: "ACTIVE_RUNTIME", sensitivity: "internal", access: "read",
  permission: "people.read", serviceOrCommand: "PeopleService", readModel: "dedicated runtime view model",
  persistence: "runtime repository", tenantIsolation: "required", masking: "none", testCoverage: "runtime test coverage",
  browserVerification: "verified in People runtime", migrationDisposition: "PRESERVE", dependencies: "trusted session and application runtime",
  notesRisks: "", ...overrides,
});

const directoryFields = ["EMPLOYEE_NUMBER", "WORK_EMAIL", "POSITION", "STATUS", "DEPARTMENT", "MANAGER", "HIRE_DATE", "AVATAR"];
const directoryCapabilities = [
  cap("PEOPLE.DIRECTORY.LIST", "List employees", { entryPoint: "/people table and cards", implementation: "PrismaPeopleDirectoryReadRepository → directory loader" }),
  cap("PEOPLE.DIRECTORY.SEARCH", "Search employees", { entryPoint: "/people search", implementation: "PeopleService.search → directory loader" }),
  cap("PEOPLE.DIRECTORY.PAGINATE", "Paginate employees", { entryPoint: "/people pagination", implementation: "PeopleService.list offset/limit" }),
  cap("PEOPLE.DIRECTORY.OPEN_PROFILE", "Open employee profile", { entryPoint: "directory row/card", implementation: "Next Link to /people/[employeeId]" }),
  ...directoryFields.map((field) => cap(`PEOPLE.DIRECTORY.VIEW_${field}`, `View directory ${field.toLowerCase().replaceAll("_", " ")}`, { entryPoint: "/people table and cards", implementation: "EmployeeDirectoryDto → PeopleDirectoryRow" })),
  cap("PEOPLE.DIRECTORY.ROW_ACTIONS", "Use directory row/card actions", { entryPoint: "runtime directory rows and cards", implementation: "RuntimeDirectoryRowActions", runtimeStatus: "ACTIVE_RUNTIME", migrationDisposition: "PRESERVE", notesRisks: "Only the safe View profile action is runtime-active; copy and Copilot remain deferred." }),
];

const trustedRuntimeCapabilities = [
  cap("PEOPLE.RUNTIME.PRISMA_READ_MODELS", "Read People directory and profiles from durable persistence", { entryPoint: "trusted server profile and directory loaders", implementation: "Prisma People read repositories", runtimeStatus: "ACTIVE_RUNTIME", access: "read", permission: "people.read", serviceOrCommand: "PrismaPeopleReadRuntime", readModel: "PeopleDirectoryReadModel and EmployeeProfileReadModel", persistence: "tenant-scoped PostgreSQL Employee reads", auditEvent: "none; reads do not create audit records", migrationDisposition: "MIGRATE_NOW", dependencies: "trusted request context, Prisma client, approved development seed", notesRisks: "No command, raw Employee, Government ID, or browser persistence capability is exposed." }),
  cap("PEOPLE.RUNTIME.TRUSTED_REQUEST_CONTEXT", "Resolve trusted People request context", { entryPoint: "server runtime loaders", implementation: "TrustedRequestContext → ApplicationRuntime", runtimeStatus: "ACTIVE_RUNTIME", permission: "people.read", serviceOrCommand: "server-owned request context adapter", readModel: "AuthenticatedPrincipal and PermissionSet", persistence: "none", migrationDisposition: "PRESERVE", dependencies: "verified server identity adapter; development adapter only outside production", notesRisks: "No browser actor, tenant, role, permission, or audit identity is trusted. Visible People capability statuses remain unchanged." }),
  cap("PEOPLE.RUNTIME.EMPLOYEE_WRITE_PORT", "Persist employee aggregate through test adapter", { entryPoint: "internal ApplicationRuntime command path only", implementation: "EmployeeAggregateRepository → InMemoryEmployeeAggregateRepository", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "CreateEmployeePersistenceHandler", persistence: "deterministic in-memory test/development adapter only", auditEvent: "none; durable audit deferred", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "trusted command policy; durable repository, transaction, and audit remain deferred", notesRisks: "No browser action reaches this adapter. It is tenant-isolated and contains no Government IDs." }),
  cap("PEOPLE.RUNTIME.EMPLOYEE_TRANSACTION", "Coordinate employee aggregate test transactions", { entryPoint: "internal ApplicationRuntime command path only", implementation: "UnitOfWork to InMemoryEmployeeUnitOfWork to transaction-scoped EmployeeAggregateRepository", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "CreateEmployeePersistenceHandler", persistence: "staged deterministic in-memory test/development transaction only", auditEvent: "none; durable audit deferred", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "trusted command policy, tenant isolation, durable transaction and audit remain deferred", notesRisks: "No browser action reaches the Unit of Work. It commits on successful internal work and rolls back failed work." }),
  cap("PEOPLE.RUNTIME.DOMAIN_EVENTS", "Collect committed employee domain events", { entryPoint: "internal ApplicationRuntime command path only", implementation: "EmployeeAggregateRoot to UnitOfWork to InMemoryDomainEventCollector", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "CreateEmployeePersistenceHandler", persistence: "ordered in-memory post-commit event collector only", auditEvent: "none; audit persistence deferred", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "trusted command policy, Unit of Work, durable outbox and publisher remain deferred", notesRisks: "No browser action creates or collects events. There is no event publishing, notification, webhook, or audit persistence." }),
  cap("PEOPLE.RUNTIME.IMMUTABLE_AUDIT", "Collect immutable committed employee audits", { entryPoint: "internal ApplicationRuntime command path only", implementation: "UnitOfWork to AuditRecordFactory to InMemoryAuditCollector", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "CreateEmployeePersistenceHandler", persistence: "ordered in-memory post-commit audit collector only", auditEvent: "none; audit persistence deferred", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "trusted command policy, Unit of Work, domain events, durable audit persistence and querying remain deferred", notesRisks: "No browser action creates or collects audits. There is no audit UI, query, SIEM integration, logging aggregation, or notification." }),
  cap("PEOPLE.RUNTIME.DURABLE_EMPLOYEE_CREATE", "Execute durable employee creation through trusted server composition", { entryPoint: "explicit trusted server entry point only", implementation: "createDurableApplicationRuntime â†’ authorization pipeline â†’ CreateEmployeeDurableHandler â†’ PrismaEmployeeUnitOfWork", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "CreateEmployeeDurableHandler", persistence: "Prisma Employee and append-only AuditRecord transaction", auditEvent: "people.employee.created", migrationDisposition: "MIGRATE_NOW", dependencies: "trusted request context, authorization policy, Railway PostgreSQL, Prisma transaction, immutable audit trigger", notesRisks: "No browser route, server action, Runtime Hire action, or public API invokes this entry point. PEOPLE.EMPLOYEE.SUBMIT remains deferred." }),
  cap("PEOPLE.RUNTIME.TRUSTED_SUBMISSION_GATEWAY", "Accept an internal trusted durable employee submission", { entryPoint: "internal server composition only", implementation: "submission gateway → authentication → authorization → durable idempotency → durable command runtime", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "submitCreateEmployee", persistence: "tenant-scoped submission idempotency record plus Prisma Employee and immutable AuditRecord", auditEvent: "people.employee.created", migrationDisposition: "MIGRATE_NOW", dependencies: "verified server authentication adapter, authorization policy, durable idempotency, Prisma transaction", notesRisks: "No route handler, server action, public API, or Runtime Hire UI invokes this gateway; browser submission remains deferred." }),
  cap("PEOPLE.RUNTIME.DURABLE_OUTBOX", "Persist committed People domain events for internal delivery", { entryPoint: "Prisma Employee Unit of Work only", implementation: "transactional OutboxMessage plus lease-guarded OutboxWorker dispatcher abstraction", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "PrismaOutboxRepository and OutboxWorker", persistence: "Prisma OutboxMessage in the Employee and Audit transaction", auditEvent: "people.employee.created", migrationDisposition: "MIGRATE_NOW", dependencies: "durable Unit of Work, domain events, PostgreSQL row locks, internal worker and dispatcher", notesRisks: "Claiming is lease-owned, stale leases can be reclaimed, and retries dead-letter after bounded attempts. No dispatcher is registered to an external vendor. There are no notifications, webhooks, email, SMS, or Slack deliveries." }),
  cap("PEOPLE.RUNTIME.DEVELOPMENT_SEED", "Seed approved synthetic People fixtures", { entryPoint: "manual npm run seed:development only", implementation: "controlled development seed transaction", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "none; operator-only development command", serviceOrCommand: "seedDevelopmentPeople", persistence: "development Tenant and Employee rows only", auditEvent: "none; development seed intentionally creates no AuditRecord", migrationDisposition: "MIGRATE_NOW", dependencies: "explicit development marker, empty development Employee table, Railway development database", notesRisks: "Never runs automatically, never resets or overwrites, and creates no audit data. It is not a browser, API, Runtime Hire, or production capability." }),
];

const directoryParityCapabilities = [
  cap("PEOPLE.EMPLOYEE.HIRE", "Prepare employee hire information", { entryPoint: "runtime directory Add employee link", implementation: "RuntimeHirePage", runtimeStatus: "ACTIVE_RUNTIME", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", persistence: "none", migrationDisposition: "MIGRATE_NOW", dependencies: "runtime route, reference loader, client-side validation, and trusted command policy", notesRisks: "The active workflow restores the visible six-step form but prepares data only; policy permits preparation without authorizing, auditing, or persisting an employee." }),
  cap("PEOPLE.EMPLOYEE.CREATE.COMMAND", "Prepare employee create command", { entryPoint: "Runtime Hire review", implementation: "CreateEmployeeCommand → authorization policy → CommandExecutionPipeline → CreateEmployeeCommandHandler", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "authorization-gated validation-only CreateEmployee command preparation", readModel: "RuntimeHireViewModel", persistence: "none; command preparation only", auditEvent: "none; durable command activation is server-only", migrationDisposition: "MIGRATE_NOW", dependencies: "trusted request context and server-owned authorization policy; the durable path is intentionally not selected by Runtime Hire", notesRisks: "The current button prepares an immutable in-memory command only after trusted permission evaluation. It never calls a repository or creates an employee." }),
  cap("PEOPLE.DIRECTORY.BULK.SELECTION", "Select directory employees", { entryPoint: "runtime row and card checkboxes", implementation: "RuntimeDirectoryPage local state", runtimeStatus: "ACTIVE_RUNTIME", serviceOrCommand: "local runtime UI state", persistence: "none", migrationDisposition: "PRESERVE", notesRisks: "Selection has only a clear action; no bulk mutation or export is enabled." }),
  cap("PEOPLE.DIRECTORY.BULK.CLEAR_SELECTION", "Clear directory selection", { entryPoint: "runtime bulk toolbar", implementation: "RuntimeDirectoryBulkToolbar", runtimeStatus: "ACTIVE_RUNTIME", serviceOrCommand: "local runtime UI state", persistence: "none", migrationDisposition: "PRESERVE" }),
  cap("PEOPLE.DIRECTORY.EXPORT", "Export directory employees", { entryPoint: "none; former legacy bulk toolbar", implementation: "not active", runtimeStatus: "DEFERRED_HIDDEN", permission: "people.directory.export", serviceOrCommand: "future authorized export service", readModel: "future DirectoryExportDto", persistence: "audited export job", auditEvent: "people.directory.exported", migrationDisposition: "MIGRATE_AFTER_AUTH", dependencies: "export policy, audit, and authenticated runtime", notesRisks: "Legacy export read raw Employee records and is not reused." }),
  ...["FILTER", "SORT", "PAGE_SIZE", "SAVED_VIEWS", "DENSITY"].map((name) => cap(`PEOPLE.DIRECTORY.${name}`, `Use directory ${name.toLowerCase().replaceAll("_", " ")}`, { entryPoint: "none; former legacy directory toolbar", implementation: "not active", runtimeStatus: "DEFERRED_HIDDEN", serviceOrCommand: name === "SAVED_VIEWS" ? "future authenticated preference service" : "future runtime directory query", persistence: name === "SAVED_VIEWS" || name === "DENSITY" ? "authenticated user preferences" : "none", migrationDisposition: name === "SAVED_VIEWS" || name === "DENSITY" ? "MIGRATE_AFTER_PERSISTENCE" : "MIGRATE_AFTER_NEW_CONTRACT", notesRisks: "Not restored by the safe parity recovery slice." })),
  ...["STATUS_CHANGE", "MANAGER_ASSIGN", "TEAM_ASSIGN"].map((name) => cap(`PEOPLE.DIRECTORY.BULK.${name}`, `Bulk ${name.toLowerCase().replaceAll("_", " ")}`, { entryPoint: "runtime bulk toolbar informational notice", implementation: "safe placeholder only", runtimeStatus: "DEFERRED_VISIBLE", access: "write", permission: `people.directory.bulk.${name.toLowerCase()}`, serviceOrCommand: "future authorized bulk command", persistence: "durable transactional repository", auditEvent: `people.directory.bulk.${name.toLowerCase()}`, migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "authorization, bulk command, and audit", notesRisks: "No mutation is currently enabled." })),
];

const hireParityCapabilities = [
  cap("PEOPLE.EMPLOYEE.HIRE.PERSONAL", "Prepare hire personal information", { entryPoint: "Runtime Hire Personal step", implementation: "RuntimeHireDraft", sensitivity: "personal", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", readModel: "RuntimeHireDraft.personal", persistence: "none", migrationDisposition: "MIGRATE_NOW", notesRisks: "Local memory only; authoritative creation remains deferred." }),
  cap("PEOPLE.EMPLOYEE.HIRE.CONTACT", "Prepare hire contact information", { entryPoint: "Runtime Hire Contact step", implementation: "RuntimeHireDraft", sensitivity: "personal", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", readModel: "RuntimeHireDraft.contact", persistence: "none", migrationDisposition: "MIGRATE_NOW" }),
  cap("PEOPLE.EMPLOYEE.HIRE.ORGANIZATION_ASSIGNMENT", "Assign hire organization references", { entryPoint: "Runtime Hire Employment step", implementation: "RuntimeHireReference loader", runtimeStatus: "DEFERRED_VISIBLE", permission: "people.employee.hire", serviceOrCommand: "future organization assignment command", readModel: "OrganizationReferenceOptionDto", persistence: "none", migrationDisposition: "MIGRATE_AFTER_NEW_CONTRACT", dependencies: "verified Entity and Business Unit reference contracts", notesRisks: "Department, Team, and Manager use the current safe reference loader; Entity and Business Unit remain visibly deferred." }),
  cap("PEOPLE.EMPLOYEE.HIRE.EMPLOYMENT", "Prepare hire employment information", { entryPoint: "Runtime Hire Employment step", implementation: "RuntimeHireDraft.employment", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", readModel: "RuntimeHireDraft.employment", persistence: "none", migrationDisposition: "MIGRATE_NOW" }),
  cap("PEOPLE.EMPLOYEE.HIRE.REPORTING_LINE", "Assign hire reporting line", { entryPoint: "Runtime Hire Manager selector", implementation: "OrganizationReferenceOptionDto", permission: "people.employee.hire", serviceOrCommand: "future reporting-line command", readModel: "OrganizationReferenceOptionDto", persistence: "none", migrationDisposition: "MIGRATE_NOW", notesRisks: "Selection is local-only until authoritative submission exists." }),
  cap("PEOPLE.EMPLOYEE.HIRE.EMERGENCY_CONTACT", "Prepare hire emergency contact", { entryPoint: "Runtime Hire Emergency Contact step", implementation: "RuntimeHireDraft.emergency", sensitivity: "personal", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", readModel: "RuntimeHireDraft.emergency", persistence: "none", migrationDisposition: "MIGRATE_NOW" }),
  cap("PEOPLE.EMPLOYEE.HIRE.GOVERNMENT_ID_ONBOARDING", "Open secure hire Government ID onboarding", { entryPoint: "Runtime Hire Government IDs step", implementation: "security-blocked placeholder", runtimeStatus: "BLOCKED_SECURITY", sensitivity: "restricted", permission: "people.government_ids.update", serviceOrCommand: "future government-ID onboarding command", readModel: "future masked GovernmentIdReadModel", persistence: "durable encrypted government-ID store", auditEvent: "employee.government_ids.onboarded", masking: "required", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "authentication, purpose-specific authorization, audit, and encrypted persistence", notesRisks: "No raw field, reveal, copy, edit, or validation is available in runtime UI." }),
  cap("PEOPLE.EMPLOYEE.HIRE.PAY_FREQUENCY", "Select hire pay frequency", { entryPoint: "Runtime Hire Employment step", implementation: "Payroll deferred placeholder", runtimeStatus: "DEFERRED_VISIBLE", sensitivity: "restricted", permission: "payroll.compensation.read", serviceOrCommand: "future Payroll shared reference service", readModel: "future PayrollPayFrequencyReferenceDto", persistence: "none", migrationDisposition: "MOVE_TO_ANOTHER_MODULE", dependencies: "Payroll ownership and shared reference contract", notesRisks: "Visible but intentionally not selectable from People." }),
  cap("PEOPLE.EMPLOYEE.HIRE.DRAFT_PERSISTENCE", "Persist hire draft", { entryPoint: "none; Runtime Hire refresh notice", implementation: "not active", runtimeStatus: "DEFERRED_HIDDEN", sensitivity: "personal", permission: "people.employee.hire", serviceOrCommand: "future authenticated draft service", readModel: "future HireDraftDto", persistence: "authenticated encrypted draft storage", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "authentication and draft retention policy", notesRisks: "Runtime form intentionally clears on refresh and never reads localStorage." }),
  cap("PEOPLE.EMPLOYEE.HIRE.REVIEW", "Review hire information", { entryPoint: "Runtime Hire Review step", implementation: "RuntimeHireDraft review groups", sensitivity: "personal", permission: "people.employee.hire", serviceOrCommand: "runtime hire preparation boundary", readModel: "RuntimeHireViewModel", persistence: "none", migrationDisposition: "MIGRATE_NOW" }),
  cap("PEOPLE.EMPLOYEE.SUBMIT", "Submit authoritative employee creation", { entryPoint: "Runtime Hire prepared review", implementation: "Runtime Hire server action to Trusted Submission Gateway to durable command runtime", runtimeStatus: "ACTIVE_RUNTIME", access: "write", permission: "people.employee.hire", serviceOrCommand: "submitRuntimeHireEmployee", readModel: "sanitized submission result", persistence: "durable idempotency record plus transactional Employee and immutable AuditRecord", auditEvent: "employee.hired", migrationDisposition: "MIGRATE_NOW", dependencies: "approved server submission adapter, trusted development authentication, authorization, Prisma transaction, idempotency", notesRisks: "Browser sends only command intent and a per-attempt idempotency key; no browser identity, tenant, permission, Government ID, or direct Prisma path is accepted." }),
];

const profileCapabilities = [
  cap("PEOPLE.PROFILE.READ", "View profile overview", { entryPoint: "/people/[employeeId]", implementation: "PeopleService.getProfile → ProfileOverviewViewModel", readModel: "ProfileOverviewViewModel" }),
  cap("PEOPLE.PROFILE.EMPLOYMENT.READ", "View employment information", { entryPoint: "/employment", implementation: "profile loader + OrganizationReferenceService", readModel: "ProfileEmploymentViewModel" }),
  cap("PEOPLE.PROFILE.WORK_INFORMATION.READ", "View work information", { entryPoint: "/work-information", implementation: "profile loader + OrganizationReferenceService", readModel: "ProfileWorkInformationViewModel" }),
  cap("PEOPLE.CONTACT.READ", "View contact information", { entryPoint: "/contact-information", implementation: "PeopleService.getContact", readModel: "ProfileContactInformationViewModel", sensitivity: "personal" }),
  cap("PEOPLE.ORGANIZATION_REFERENCES.READ", "Resolve organization references", { entryPoint: "Employment and Work Information", implementation: "OrganizationReferenceService" }),
  cap("PEOPLE.PROFILE.HEADER.READ", "View profile header", { entryPoint: "profile shell", implementation: "ProfileOverviewViewModel" }),
  cap("PEOPLE.PROFILE.TABS.NAVIGATE", "Navigate profile tabs", { entryPoint: "ProfileNav", implementation: "runtime tab links" }),
  cap("PEOPLE.PROFILE.HISTORICAL_ROUTES.OPEN", "Open direct historical tab URLs", { entryPoint: "deferred routes", implementation: "RuntimeProfilePage deferred state", runtimeStatus: "DEFERRED_VISIBLE" }),
  ...["LOADING", "UNAVAILABLE", "UNAUTHORIZED", "NOT_FOUND"].map((state) => cap(`PEOPLE.PROFILE.STATE.${state}`, `View profile ${state.toLowerCase()} state`, { entryPoint: "profile route", implementation: "RuntimeProfilePage result state" })),
];

const governmentLabels = ["TIN", "SSS", "PHILHEALTH", "PAGIBIG"];
const governmentRead = governmentLabels.map((label) => cap(`PEOPLE.GOVERNMENT_IDS.READ_MASKED.${label}`, `View masked ${label === "PAGIBIG" ? "Pag-IBIG" : label}`, {
  entryPoint: "historical Overview/Government IDs tab", implementation: "legacy Employee.governmentIds", runtimeStatus: "DEFERRED_VISIBLE", sensitivity: "restricted", permission: "people.government_ids.read", serviceOrCommand: "PeopleService.getGovernmentIds", readModel: "future masked GovernmentIdReadModel", persistence: "durable encrypted government-ID store", auditEvent: "employee.government_ids.viewed", masking: "required", migrationDisposition: "MIGRATE_AFTER_AUTH", dependencies: "authentication, masked DTO, audit repository", notesRisks: "EmployeeGovernmentIdsDto contains raw values and must never be sent to the browser."
}));
const governmentCapabilities = [
  ...governmentRead,
  cap("PEOPLE.GOVERNMENT_IDS.TAB.OPEN", "Open Government IDs tab", { entryPoint: "/government-ids", implementation: "safe runtime deferred page", runtimeStatus: "DEFERRED_VISIBLE", sensitivity: "restricted", migrationDisposition: "MIGRATE_AFTER_AUTH", notesRisks: "Current page intentionally exposes no identifier values." }),
  ...["REVEAL", "HIDE", "COPY"].map((action) => cap(`PEOPLE.GOVERNMENT_IDS.${action}`, `${action[0]}${action.slice(1).toLowerCase()} full identifier`, { entryPoint: "legacy GovIdManager", implementation: "legacy client handler", runtimeStatus: "BLOCKED_SECURITY", sensitivity: "restricted", permission: `people.government_ids.${action.toLowerCase()}`, serviceOrCommand: "future government-ID access command", readModel: "masked GovernmentIdReadModel", persistence: "durable encrypted government-ID store", auditEvent: `employee.government_ids.${action.toLowerCase()}`, masking: "required", migrationDisposition: "MIGRATE_AFTER_AUTH", dependencies: "purpose-specific permission and immutable audit", notesRisks: "Full values are never browser defaults." })),
  ...["UPDATE", "VERIFY", "REJECT"].map((action) => cap(`PEOPLE.GOVERNMENT_IDS.${action}`, `${action[0]}${action.slice(1).toLowerCase()} identifier`, { entryPoint: "legacy GovIdManager", implementation: "legacy store/localStorage handler", runtimeStatus: "BLOCKED_SECURITY", sensitivity: "restricted", access: "write", permission: `people.government_ids.${action.toLowerCase()}`, serviceOrCommand: "future government-ID command", persistence: "durable encrypted government-ID and verification history", auditEvent: `employee.government_ids.${action.toLowerCase()}d`, masking: "required", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE", dependencies: "authorized command, durable transaction, audit", notesRisks: "Legacy writes bypassed PeopleService; update must not use read permission." })),
  cap("PEOPLE.GOVERNMENT_IDS.CANCEL", "Cancel local Government ID action", { entryPoint: "legacy GovIdManager", implementation: "local state close", runtimeStatus: "DEFERRED_VISIBLE", sensitivity: "restricted", permission: "people.government_ids.read", serviceOrCommand: "local UI state", persistence: "none", masking: "required", migrationDisposition: "MIGRATE_AFTER_AUTH" }),
  cap("PEOPLE.GOVERNMENT_IDS.VERIFICATION_METADATA.READ", "View Government ID verification status and metadata", { entryPoint: "legacy GovIdManager", implementation: "legacy localStorage verification store", runtimeStatus: "BLOCKED_SECURITY", sensitivity: "restricted", permission: "people.government_ids.read", serviceOrCommand: "future verification read service", readModel: "future GovernmentIdVerificationReadModel", persistence: "durable verification history", auditEvent: "employee.government_ids.verification_viewed", masking: "required", migrationDisposition: "MIGRATE_AFTER_PERSISTENCE" }),
];

const profileActions = [
  ["PROFILE.UPDATE", "Edit profile", "people.profile.write", "employee.profile.updated", "MIGRATE_AFTER_AUTH"],
  ["CONTACT.UPDATE", "Update contact information", "people.contact.write", "employee.contact.updated", "MIGRATE_AFTER_AUTH"],
  ["EMERGENCY_CONTACTS.UPDATE", "Update emergency contacts", "people.emergency_contacts.write", "employee.emergency_contacts.updated", "MIGRATE_AFTER_AUTH"],
  ["EMPLOYMENT.PROMOTE", "Promote employee", "people.employment.promote", "employee.promoted", "MIGRATE_AFTER_PERSISTENCE"],
  ["EMPLOYMENT.TRANSFER", "Transfer employee", "people.employment.transfer", "employee.transferred", "MIGRATE_AFTER_PERSISTENCE"],
  ["COMPENSATION.CHANGE", "Change compensation", "payroll.compensation.write", "employee.compensation.changed", "MOVE_TO_ANOTHER_MODULE"],
  ["EMPLOYMENT.REGULARIZE", "Regularize employee", "people.employment.regularize", "employee.regularized", "MIGRATE_AFTER_PERSISTENCE"],
  ["REPORTING_LINE.CHANGE", "Change manager", "people.reporting_line.write", "employee.manager.changed", "MIGRATE_AFTER_PERSISTENCE"],
].map(([id, name, permission, auditEvent, migrationDisposition]) => cap(`PEOPLE.${id}`, name, { entryPoint: "legacy profile Actions menu", implementation: "legacy drawer + usePeopleRepository", runtimeStatus: id === "COMPENSATION.CHANGE" ? "DEFERRED_HIDDEN" : "DEFERRED_HIDDEN", sensitivity: id === "COMPENSATION.CHANGE" ? "restricted" : "personal", access: "write", permission, serviceOrCommand: "future authorized People command", persistence: "durable transactional repository", auditEvent, migrationDisposition: migrationDisposition as MigrationDisposition, dependencies: "authentication, command authorization, audit and persistence", notesRisks: "Legacy action bypasses application service and mock actor identity." }));

const legacyMethods = ["SUSPEND", "REACTIVATE", "TERMINATE", "OFFBOARD"].map((name) => cap(`PEOPLE.EMPLOYMENT.${name}`, `${name[0]}${name.slice(1).toLowerCase()} employee`, { entryPoint: "none; legacy repository method only", implementation: "usePeopleRepository", runtimeStatus: "PLANNED", sensitivity: "restricted", access: "write", permission: `people.employment.${name.toLowerCase()}`, serviceOrCommand: "future product-approved lifecycle command", persistence: "durable transactional repository", auditEvent: `employee.${name.toLowerCase()}d`, migrationDisposition: "RETIRE_WITH_APPROVAL", dependencies: "product approval, authorization, audit", notesRisks: "Not approved merely because a legacy method exists; reclassify after product decision." }));

const deferredTabs = ["COMPENSATION", "GOVERNMENT_IDS", "DOCUMENTS", "TIMELINE", "NOTES", "EMERGENCY_CONTACTS", "ASSETS"].map((name) => cap(`PEOPLE.PROFILE.TAB.${name}`, `Open ${name.toLowerCase().replaceAll("_", " ")} tab`, { entryPoint: `/people/[employeeId]/${name.toLowerCase().replaceAll("_", "-")}`, implementation: "RuntimeProfileDeferredTab", runtimeStatus: "DEFERRED_VISIBLE", migrationDisposition: name === "COMPENSATION" ? "MOVE_TO_ANOTHER_MODULE" : "MIGRATE_AFTER_NEW_CONTRACT", notesRisks: "Safe placeholder only; no legacy loader is active." }));

export const BUSINESS_CAPABILITIES: readonly BusinessCapability[] = [...trustedRuntimeCapabilities, ...directoryCapabilities, ...directoryParityCapabilities, ...hireParityCapabilities, ...profileCapabilities, ...governmentCapabilities, ...profileActions, ...legacyMethods, ...deferredTabs];
