import type { AuditRepository } from "@/platform/audit";
import type { EmployeeRepository } from "@/platform/people/employee-repository";
import { createServiceToken } from "@/platform/di";
import type { PeopleService } from "@/platform/people/application/people-service";
import type { OrganizationReferenceRepository } from "@/platform/organization/organization-reference-repository";
import type { OrganizationReferenceService } from "@/platform/organization/organization-reference-service";
import type { EmployeeAggregateRepository } from "@/platform/people/persistence/employee-aggregate-repository";
import type { EmployeeTransactionRepositories } from "@/platform/people/persistence/in-memory-employee-unit-of-work";
import type { UnitOfWork } from "@/platform/transactions/unit-of-work";
import type { DomainEventCollector } from "@/platform/events/domain-event-collector";
import type { AuditCollector } from "@/platform/auditing/audit-collector";
import type { AuditRecordFactory } from "@/platform/auditing/audit-record-factory";
export const AUDIT_REPOSITORY = createServiceToken<AuditRepository>("AuditRepository");
export const EMPLOYEE_REPOSITORY = createServiceToken<EmployeeRepository>("EmployeeRepository");
export const PEOPLE_SERVICE = createServiceToken<PeopleService>("PeopleService");
export const ORGANIZATION_REFERENCE_REPOSITORY = createServiceToken<OrganizationReferenceRepository>("OrganizationReferenceRepository");
export const ORGANIZATION_REFERENCE_SERVICE = createServiceToken<OrganizationReferenceService>("OrganizationReferenceService");
export const EMPLOYEE_AGGREGATE_REPOSITORY = createServiceToken<EmployeeAggregateRepository>("EmployeeAggregateRepository");
export const EMPLOYEE_UNIT_OF_WORK = createServiceToken<UnitOfWork<EmployeeTransactionRepositories>>("EmployeeUnitOfWork");
export const DOMAIN_EVENT_COLLECTOR = createServiceToken<DomainEventCollector>("DomainEventCollector");
export const AUDIT_COLLECTOR = createServiceToken<AuditCollector>("AuditCollector");
export const AUDIT_RECORD_FACTORY = createServiceToken<AuditRecordFactory>("AuditRecordFactory");
